# Generated by Django 6.1.1 on 2026-09-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
    ]
